#!/usr/bin/env bash

# HO.

TAGGER="/tmp/buildtagger"
REPO_ROOT="/Users/alper/data/workspaces/github.com/ulucinar/upbound/provider-gcp"

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/.+\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/zz_groupversion_info\.go" --tag-format "(%s || register || all) && !ignore_autogenerated" --mode dir

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "zz_(register)\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode file

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "(.+)/.+/zz_controller\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "zz_(.+)_setup\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode file
